### ISSUE TITLE
Would you consider releasing the annotations of single object tracking?

### ISSUE THREAD

**Issue by jackydinosaur** [Ben93kie/SeaDronesSee#29]
Hello, thanks for the great work !!
Would you consider releasing the annotations of single object tracking?
I would like to do further research on single object tracking.
I am considering using this dataset for my master's research

I am looking forward to your reply.

**Comment by Ben93kie** [comment]
Hi, thanks for your interest!
The annotations for the train and val set are available already. The annotations for the test set are not planned to be released currently. However, you can submit your predictions on the webserver to get feedback on your performance. However, at the moment the upload option is closed because of the end of a challenge. It will open soon again. Let me know when you want to upload something, then I can open it even earlier.

**Comment by Ben93kie** [comment]
Inactivity
